### ISSUE TITLE
代码中的小问题

### ISSUE THREAD

**Issue by AHikers** [BeijiYang/minaSmsVerification#1]
在node 的msg.js文件中，第二十六行应为TemplateParam: `${'{"number":"' + smsCode + '"}'}`，作者少了一个双引号，导致发送短信时接口出现参数不对的错误

**Comment by BeijiYang** [comment]
之前的写法不好，而且有个问题：传入的验证码必须是JSON串格式，否则当字符串开头是0时，0会被忽略掉，得到小于6位的验证码

现已更新

```
TemplateParam: `{"number":${jsonifySmsCode}}`
```
