### ISSUE TITLE
isv.SMS_CONTENT_ILLEGALError 

### ISSUE THREAD

**Issue by liaocpen** [BeijiYang/minaSmsVerification#3]
您好，遇到个问题就是 偶尔可以发送成功
单多数会出现这样的提示
  "name": "isv.SMS_CONTENT_ILLEGALError",
        "data": {
            "Message": "短信内容非法",
            "RequestId": "6AC1E2C3-9226-456D-A02C-E9C1707E31EC",
            "Code": "isv.SMS_CONTENT_ILLEGAL"
        }
请问有遇到过么？

**Comment by BeijiYang** [comment]
您好。这个问题我没有遇到过。这看起来像是阿里云服务相关配置的问题，他们有个列表集中展示了各种错误码对应的情况，还有工单系统可以人工咨询。建议你可以去看看。

**Comment by myncepu** [comment]
@liaocpen 我也遇到了这个错误，不知道你找到原因了没有？

**Comment by liaocpen** [comment]
> @liaocpen 我也遇到了这个错误，不知道你找到原因了没有？

这个原因是服务器在境外 你把服务换个服务器搭就好了或者要买境外的短信服务

**Comment by ShenChen1995** [comment]
请问作者，怎么样换个服务器搭啊
你说找认识的人在中国使用吗
